GET http://localhost:4000/products



###


GET http://localhost:3400/products/622762227ea02b0d827c6282


###


POST http://localhost:4000/products 
Content-Type: application/json

{
    "title": "Rare Candy",
    "price": 330,
    "category": "Pokémon Items",
    "img": "https://i.postimg.cc/qq0JGX0d/rare-candy.jpg",
    "description": "Using a Rare Candy on a Pokémon raises the Pokémon's level by 1, ending up with the minimum amount of Experience Points of that level after leveling up. It also raises the Pokémon's friendship by a little."
}



###


DELETE http://localhost:3400/products/6228708343165ede13a49f43


###



PATCH http://localhost:3400/products
Content-Type: application/json

{
    
}


###

GET http://localhost:4000/api/test/all


###
POST http://localhost:4000/api/auth/signup
Content-Type: application/json

{
    "username":"kyle",
    "email":"kylemcb.24@gmail.com",
    "password":"admin",
    "roles":["admin" , "user"]

}

###
POST http://localhost:4000/api/auth/signin
Content-Type: application/json

{
    "username":"kyle",
    "password":"admin"

}

###
GET http://localhost:4000/api/test/admin
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmM1YmYxMmIwNjYxNzYxN2E3YTQxNCIsImlhdCI6MTY0NzA3NDQ4OSwiZXhwIjoxNjQ3MTYwODg5fQ.kqoZksOZznX428v67L43HjsX8vtale4-KzmoCVONOXQ


###
DELETE http://localhost:4000/api/delete/622c5bf12b06617617a7a414
Content-Type: application/json


###
PATCH http://localhost:4000/users/622c5bf12b06617617a7a414

{
    "username": "Kyle"
}